# Generated by Django 5.0 on 2024-07-20 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apicrud', '0002_excelupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='excelupload',
            name='excel_file_upload',
            field=models.FileField(upload_to='excel/'),
        ),
    ]
