# Generated by Django 5.0 on 2024-07-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='pass1',
            field=models.CharField(default='temporary_value', max_length=20),
        ),
        migrations.AddField(
            model_name='student',
            name='pass2',
            field=models.CharField(default='temporary_value', max_length=20),
        ),
    ]
